services:
        - docker
before_install:
        - docker build -t urira/multi-docker -f ./client/Dockerfile.dev .
scripts:
        - docker run  -e CI=true urira/multi-docker npm run test -- --coverage
