services:
        - docker
before_install:
        - docker build -t urira/react-test -f ./client/Dockerfile.dev ./client
scripts:
        - docker run  -e CI=true urira/react-test npm run test -- --coverage
